name: 'merge-bump-release'
description: 'GitHub action to be applied on merged pull-request, to bump a semver and create a new release'
inputs:
  github_token:
    description: 'Secret GitHub token'
    required: true
  tag_prefix:
    description: 'A prefix to add to the tag, defaults to empty'
    required: false
    default: ''
  bump:
    description: 'Bump type to determine which part of the SemVer will be increased. Can be one of: minor/major/patch. Will default to patch, unless other mechanisms of determining these were defined'
    required: false
  infer_bump_from_commit:
    description: 'If set to true, looks for major, minor, patch in the commit in order to determine the bump.'
    required: false
  update_file:
    description: 'Choose the file you want to update'
    required: false
  changelog:
    description: 'Update changelog'
    required: false
    default: true

outputs:
  next_version: # id of output
    description: 'The next version name (including the prefix)'
runs:
  using: 'node16'
  main: 'dist/index.js'
