name: Closed and merged Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  bump-release:
    name: Bump release
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and release
        uses: ultimateai/bump-action@v0.5.4
        with:
          github_token: ${{ secrets.ULTIMATE_GITHUB_PAT }}
          infer_bump_from_commit: true
          update_file: package.json
          changelog: true
          initial_release: "0.0.0"
